DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userid INTEGER NOT NULL,
  latitude INTEGER,
  longitude INTEGER,
  freeword TEXT,
  FOREIGN KEY (userid) REFERENCES user (id)
);